spring.application.name=chatloop
spring.main.web-application-type=none

spring.ai.vectorstore.qdrant.initialize-schema=true

# Replace these paths with paths to a documents of your choice
rag.documents=classpath:/documents/camp-bowwow.txt,classpath:/documents/frog-panic.txt,classpath:/documents/taco-truck.txt

java-vectors.storage-path=/tmp/vectors/rag-recipe
