spring.application.name=typesafe-intro

# For Nimble on Ollama
spring.ai.typesafe.base-url=http://localhost:11434
spring.ai.typesafe.model=nimble

# For locally run Laya
#spring.ai.typesafe.base-url=http://localhost:8000
#spring.ai.typesafe.model=english

# Needed solely to enable auto-configuration
spring.ai.typesafe.api-key=bogus_api_key