spring.application.name=chatloop
spring.main.web-application-type=none

spring.ai.vectorstore.qdrant.initialize-schema=true

# Replace this path with the path to a document of your choice
rag.document.url=file:///Users/habuma/Documents/BoardGameRules/Sagrada.pdf