spring.application.name=semantic-caching
spring.main.web-application-type=none

logging.level.org.springframework.ai.vectorstore.redis.cache.semantic.DefaultSemanticCache=debug

semantic.cache.similarity-threshold=0.8

spring.docker.compose.stop.command=down
spring.docker.compose.stop.arguments=--volumes
