spring.application.name=logging
spring.main.web-application-type=none
logging.level.root=error
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=error
logging.level.org.zalando=trace